"""empty message

Revision ID: ad1d28fbc98b
Revises: 0175c29da1fb
Create Date: 2019-02-22 11:35:33.833644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad1d28fbc98b'
down_revision = '0175c29da1fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'teachers', ['teacher_id'], ['id'])
    op.drop_column('courses', 'teacher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('teacher', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'teacher_id')
    # ### end Alembic commands ###
